version: "3"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
      - composer
    ports:
      - 8070:80

  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: testind_docker
      MYSQL_USER: admin_testind_docker
      MYSQL_PASSWORD: admin_testind_docker
    ports:
      - 3307:3306
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin

  composer:
    container_name: composer
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - .:/app

  node:
    container_name: node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/usr/src/app/node_modules
      - ./web:/usr/src/app/public
    command: /usr/src/app/entrypoint.sh