version: "3"
services:
  web:  # Define a container to hold the web application
    container_name: web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
      - composer
    ports:
      - 8070:80

  db: # Holds the Database used by the application.
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: testind_docker
      MYSQL_USER: admin_testind_docker
      MYSQL_PASSWORD: admin_testind_docker
    ports:
      - 3307:3306

  phpmyadmin: # Holds a web interface to administrate the Database.
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin

  composer: # Holds the composer manager.
    container_name: composer
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - .:/app

  node: # Holds a running installation of node
    container_name: node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/usr/src/app/node_modules # Publish `node_modules` folder to the host. Contains those used dependencies (js, css, etc...)
      - ./web:/usr/src/app/public   # Publish `public` folder to the host Contains those  compressed files used by the application (js, css)
    command: /usr/src/app/entrypoint.sh 